### PR TITLE
corrected the typos and added the manual check in python script

### LINKED ISSUE #133: clean typo in tests json
**Use Case**

Our smoke tests currently use a Python script to execute a JSON test suite. When specifying a query that needs automatic shutdown, the script checks for `"terminate": "auto"` in the JSON phase. The detailed script logic for checking `"terminate"` is in this code:
https://github.com/timeplus-io/proton/blob/057bfda9c9584f5ed6dc874d30e4fa2fcea9aafe/tests/stream/helpers/rockets.py#L2865-L2870

The issue is that our JSON contains a typo for terminate:

https://github.com/timeplus-io/proton/blob/057bfda9c9584f5ed6dc874d30e4fa2fcea9aafe/tests/stream/test_stream_smoke/0009_stream_join_stream_case2.json#L21

It has `"manuel"` instead of `"manual"`.

**Proposed Solution**

We should clean up the related Python script as well. The default condition only checks for `"auto"`, so we are currently skipping over this typo.

### PR DESCRIPTION
**Pull request by varshneydevansh**
PR checklist:
- Did you run ClangFormat ?
   Did not required as I made changes to the JSON files and a single Python file.
- Did you separate headers to a different section in existing community code base ? 
   Probably not required.
- Did you surround `proton: starts/ends` for new code in existing community code base ?
   Probably not required.

Please write user-readable short description of the changes:

- Fixes #133 

This PR tries to fix the typos made in the smoke tests JSON file as because of which we have a default condition only checks for "auto", so we are currently skipping because of these typos.

### CODE REVIEW

**Comment by yokofly** [comment]
thanks for your contribution, just one confirm, have you tried locally the change works?
you can pull proton image like below
```
docker run -it --rm  --network host ghcr.io/timeplus-io/proton:1.4.2-rc
```

and into folder 
```
proton/tests/stream$ python3 ci_runner.py --local --no_retry -q udf
```

`-q` means run the related query suite. in the json `suite name` style.

**Comment by varshneydevansh** [comment]
I haven't tried yet. Trying it locally

EDIT -

Which API key should I use? 

```bash
 [~/proton/tests/stream]
 ✘  devansh   133_clean_typo_tests_json  sudo docker ps                                                                       
[sudo] password for devansh: 
CONTAINER ID   IMAGE                                 COMMAND            CREATED          STATUS          PORTS     NAMES
0f00e3c67a58   ghcr.io/timeplus-io/proton:1.4.2-rc   "/entrypoint.sh"   10 minutes ago   Up 10 minutes             youthful_khayyam
               

 [~/proton/tests/stream]
 devansh   133_clean_typo_tests_json  python3 ci_runner.py --local --no_retry -q udf
ci_runner starting: run_mode = local, loop = 1, logging_level=ERROR, test_retry = False, test_suite_timeout = 900, test_folders = test_stream_smoke starts
args_dict = {'run_mode': 'local', 'debug': False, 'test_folders': 'test_stream_smoke', 'test_suites': 'udf', 'id': 'None', 'loop': 1, 'settings': 'default', 'cluster_query_route_mode': 'None', 'cluster_query_node': 'None', 'create_stream_shards': 'None', 'create_stream_replicas': 'None', 'no_retry': True, 'test_suite_timeout': 900, 'tmp': 'None'}
one of TIMEPLUS_API_KEY,TIMEPLUS_ADDRESS,TIMEPLUS_WORKSPACE is not found in ENV
proton_server_container_name_list = ['proton-server']
ERROR: usage: ci_runner.py [options] [file_or_dir] [file_or_dir] [...]
ci_runner.py: error: unrecognized arguments: --self-contained-html test_stream_smoke
  inifile: None
  rootdir: /home/devansh/proton/tests/stream

setting = default, setting_test_duration = 2
(('proton-server', 'proton-server://var/log/proton-server/proton-server.log'), ('proton-server', 'proton-server://var/log/proton-server/proton-server.err.log'))
file_tuple = ('proton-server', 'proton-server://var/log/proton-server/proton-server.log')
file_name = default-proton-server-proton-server.log
Copying proton-server://var/log/proton-server/proton-server.log, command = docker cp proton-server://var/log/proton-server/proton-server.log ./default-proton-server-proton-server.log
Got execption copying file Command 'docker cp proton-server://var/log/proton-server/proton-server.log ./default-proton-server-proton-server.log' returned non-zero exit status 1. 
file_tuple = ('proton-server', 'proton-server://var/log/proton-server/proton-server.err.log')
file_name = default-proton-server-proton-server.err.log
Copying proton-server://var/log/proton-server/proton-server.err.log, command = docker cp proton-server://var/log/proton-server/proton-server.err.log ./default-proton-server-proton-server.err.log
Got execption copying file Command 'docker cp proton-server://var/log/proton-server/proton-server.err.log ./default-proton-server-proton-server.err.log' returned non-zero exit status 1. 
ci_runner: downloaded_log_files_paths = ()
ci_runner: local mode, no report uploaded.

```

**Comment by yokofly** [comment]
Sorry i am busy in a meeting, later reply

**Comment by yokofly** [comment]
Hi, running the test suite locally is not required for the API key. this message is confusing (sorry about this)


below is my output in my locally
```
proton/tests/stream$ python3 ci_runner.py --local --no_retry -q udf
ci_runner starting: run_mode = local, loop = 1, logging_level=ERROR, test_retry = False, test_suite_timeout = 900, test_folders = test_stream_smoke starts
args_dict = {'run_mode': 'local', 'debug': False, 'test_folders': 'test_stream_smoke', 'test_suites': 'udf', 'id': 'None', 'loop': 1, 'settings': 'default', 'cluster_query_route_mode': 'None', 'cluster_query_node': 'None', 'create_stream_shards': 'None', 'create_stream_replicas': 'None', 'no_retry': True, 'test_suite_timeout': 900, 'tmp': 'None'}
one of TIMEPLUS_API_KEY,TIMEPLUS_ADDRESS,TIMEPLUS_WORKSPACE is not found in ENV
proton_server_container_name_list = ['proton-server']
=================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.15, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- miniconda3/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.15', 'Platform': 'Linux-5.15.0-92-generic-x86_64-with-glibc2.17', 'Packages': {'pytest': '6.2.5', 'pluggy': '1.0.0'}, 'Plugins': {'metadata': '2.0.4', 'cases': '3.6.5', 'html': '3.1.1'}}
rootdir: /proton/tests/stream
plugins: metadata-2.0.4, cases-3.6.5, html-3.1.1
collecting ... pytest_generate_tests: config_file_path = /proton/tests/stream/test_stream_smoke/configs/config.json
env_check: health_url = http://localhost:3218/proton/ping
env_check: env_health_check_res: True
proton_setting = default, test_suite = udf, proton_server_container_name = proton-server, test_retry = False, test_suite_timeout = 900,test_event_tag = None, query_states_dict = {'test_suite_name': 'udf', 'proton_setting': 'default', 'proton_server_container_name': 'proton-server'}, test_running starts......
check depends_on_stream_list = ['udf_types'], all found
check depends_on_stream_list = ['udf_types'], all found

```

if I add extra commands will give the previously posted error
```
/proton/tests/stream$ python3 ci_runner.py --local --no_retry -q udf  --self-contained-html test_stream_smoke
usage: ci_runner.py [-h] [--github | --local] [--debug] [-d TEST_FOLDERS] [-q TEST_SUITES] [-i ID] [--loop LOOP] [-s SETTINGS] [--cluster_query_route_mode CLUSTER_QUERY_ROUTE_MODE]
                    [--cluster_query_node CLUSTER_QUERY_NODE] [--create_stream_shards CREATE_STREAM_SHARDS] [--create_stream_replicas CREATE_STREAM_REPLICAS] [--no_retry]
                    [--test_suite_timeout TEST_SUITE_TIMEOUT] [--tmp TMP]
ci_runner.py: error: unrecognized arguments: --self-contained-html test_stream_smoke

```

one final check, have you install the pip package dependency?
step 1: Install python dependencies, get the requirements.txt from tests/stream/helpers and run pip -r requirements.txt
step 2: Running the test suite locally.
more detailed check the wiki https://github.com/timeplus-io/proton/wiki/Stream-Smoke-Test

**Comment by yokofly** [comment]
I do not think the CI failure is related to this PR, I tested with locally all is good. I will check a bit later

**Comment by varshneydevansh** [comment]
Thanks for the requirements.txt I should have searched for that file completely forgot my bad. After getting things done with the requirements.txt file got stuck with py.xml error but it got resolved. I did run the local test and here are the result of that -

```bash
------------------------------- generated html file: file:///home/devansh/proton/tests/stream/report_default_2024-02-05 18:35:40.356965.html -------------------------------
====================================================================== 21 passed in 400.53s (0:06:40) ======================================================================
setting = default, setting_test_duration = 403
(('proton-server', 'proton-server://var/log/proton-server/proton-server.log'), ('proton-server', 'proton-server://var/log/proton-server/proton-server.err.log'))
file_tuple = ('proton-server', 'proton-server://var/log/proton-server/proton-server.log')
file_name = default-proton-server-proton-server.log
Copying proton-server://var/log/proton-server/proton-server.log, command = docker cp proton-server://var/log/proton-server/proton-server.log ./default-proton-server-proton-server.log
Got execption copying file Command 'docker cp proton-server://var/log/proton-server/proton-server.log ./default-proton-server-proton-server.log' returned non-zero exit status 1. 
file_tuple = ('proton-server', 'proton-server://var/log/proton-server/proton-server.err.log')
file_name = default-proton-server-proton-server.err.log
Copying proton-server://var/log/proton-server/proton-server.err.log, command = docker cp proton-server://var/log/proton-server/proton-server.err.log ./default-proton-server-proton-server.err.log
Got execption copying file Command 'docker cp proton-server://var/log/proton-server/proton-server.err.log ./default-proton-server-proton-server.err.log' returned non-zero exit status 1. 
ci_runner: downloaded_log_files_paths = ()
ci_runner: local mode, no report uploaded.
```

## It's passing 21 tests.
```bash
proton_setting = default, Test_Suites_Running_Statistics:                                                                                                                                                     

test_stream_smoke/test_query_smoke.py::test_run[udf-0-scalar_udf_basic] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-1-uda_without_emit_strategy] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-2-with_emit_strategy] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-3-no_key_with_emit_strategy] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-4-uda_substream_without_emit_strategy] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-5-substream_with_emit_strategy] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-6-toggle_bool] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-7-emit_two_times] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-8-not_all_groups_emit] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-9-result_with_wrong_type] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-10-uda_with_another_aggregate] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-11-uda_with_emit_in_hist_query] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-12-missing_arg] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-13-incorrect_arg_type] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-14-uda_throws_exception_when_process] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-15-uda_throws_exception_when_finalize] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-16-scalar_udf_exception] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-17-scalar_udf_no_return] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-18-scalar_udf_missing_arg] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-19-scalar_udf_incorrect_arg_type] PASSED
test_stream_smoke/test_query_smoke.py::test_run[udf-20-uda_no_return] PASSED

```

**Comment by jovezhong** [comment]
Thank you for contributing this improvement, @varshneydevansh 🙏

**Comment by yokofly** [comment]
@varshneydevansh do not worry, the CI failure is unrelated to this PR, I am still trying to fix the security in github action secrets.
We previously have not tested the workflow running outside (sad, but you are the first one to open a new pr to start workflow I guess :+1: ).

**Comment by varshneydevansh** [comment]
> @varshneydevansh do not worry, the CI failure is unrelated to this PR, I am still trying to fix the security in github action secrets. We previously have not tested the workflow running outside (sad, but you are the first one to open a new pr to start workflow I guess 👍 ).

Oh didn't know I was the first to open the PR 💯 :-)

**Comment by yokofly** [comment]
> > @varshneydevansh do not worry, the CI failure is unrelated to this PR, I am still trying to fix the security in github action secrets. We previously have not tested the workflow running outside (sad, but you are the first one to open a new pr to start workflow I guess 👍 ).
> 
> Oh didn't know I was the first to open the PR 💯 :-)

actually, we have other pr previously, but not open workflow. because the pr just modifies readme such things, no need to build whole proton in one hour.

**Pull request merged**
