### PR TITLE
specify the data gen image version

### PR DESCRIPTION
**Pull request by gangtao**
for the fraud datagen, new version has more features more is not required for this demo, so we tag specific version for datagen

### CODE REVIEW

**Comment by yokofly** [comment]
hi @gangtao the CI failure in some unrelated error, your change shall not related to fail:)
I opened issue about CI fail here https://github.com/timeplus-io/proton/issues/393
if necessary, you can call Jove to force merge.

**Comment by yokofly** [comment]
proton requires the first-time contribution need to assign CLA, and the commit author needs to set the email address.

but I expected this PR shall be merge first cause it do nothing with our code base, running CI is cost.

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).

**Pull request merged**
