### PR TITLE
External Stream: Add Support for Apache Pulsar

### PR DESCRIPTION
**Pull request by Kartik1397**
PR checklist:
- Did you run ClangFormat ?
No (TODO)
- Did you separate headers to a different section in existing community code base ?
No (TODO)
- Did you surround `proton: starts/ends` for new code in existing community code base ?
No (TODO)

Please write user-readable short description of the changes:
TODO

Checklist:
- [x] Setup dev environment
- [x] Setup code auto completion
- [x] Working skeleton code
- [x] Evaluate KoP
- [ ] Pulsar integration
    - [x] Add Pulsar in deps
    - [x] Pulsar client setup
    - [ ] Pulsar consumer setup
    - [x] Pulsar topic validation
    - [ ] Read from pulsar & stream
    - [ ] Write to pulsar & stream
- [ ] Add test cases

/claim #338

### CODE REVIEW

**Comment by jovezhong** [comment]
Congratulations, @Kartik1397 , for submitting the first PR to Timeplus Proton.

I am assigning @zliang-min as the reviewers, since he is the main person behind Kafka External Stream and ClickHouse External Table. Once this is PR is ready to review, let us know.

**Comment by jovezhong** [comment]
Hi @Kartik1397 , I'd like to check with you about the progress of the external stream for Apache Pulsar. Can you give us a rough percentage of readiness? Say 50%, more or less? We got some customer requirements to use such Pulsar integration in our core engine. So we need to prioritize it.

**Comment by Kartik1397** [comment]
Hi @jovezhong , In terms of progress I'm still at 40%. I can read from pulsar to proton but I'm facing issues while streaming result back to client. So, I was exploring TCPHandler & Serialisation part of proton since past few days. Attached exact error if anyone is interested. Write to pulsar is completely pending.

If someone else want to finish remaining parts, I'm okay with it. I've pushed all the code changes I've done till now in this PR.

Current blocker:
```
Code: 49. DB::Exception: Received from localhost:8463. DB::Exception: Bad cast from type DB::ColumnVector<char8_t> to DB::ColumnString. (LOGICAL_ERROR)
```

**Comment by jovezhong** [comment]
Hi @Kartik1397 , thanks for sharing the progress and issue. @zliang-min  will work on this feature and he can take a look at your current code and provide some support. Are you on our community slack https://timeplus.com/slack ? Maybe we can have a group chat/meeting there.

**Comment by Kartik1397** [comment]
Sure @jovezhong, I'm on the slack. **Kartik Prajapati** is my username.

**Comment by jovezhong** [comment]
Close this WIP PR. We will build a MVP in our commercial offering and get feedbacks

**Pull request closed without merging**
