### PR TITLE
Backport/issue 6299 fix native mac os build (#6300) (#6468)

### PR DESCRIPTION
**Pull request by qijun-niu-timeplus**
* Merge pull request #51710 from velavokr/velavokr-warn-cpu-utilization

A cmake warning on job limits underutilizing CPU

* Merge pull request #52196 from rschu1ze/simplify-job-limiting

CMake: Simplify job limiting

* Merge pull request #56971 from ClickHouse/own-cmake-for-grpc

Own CMake for GRPC

* Merge pull request #70671 from ClickHouse/fix-native-macos

Fix native macOS build

---------

PR checklist:
- Did you run ClangFormat ?
- Did you separate headers to a different section in existing community code base ?
- Did you surround `proton: starts/ends` for new code in existing community code base ?

Please write user-readable short description of the changes:

### CODE REVIEW

**Comment by yokofly** [comment]
@qijun-niu-timeplus  missing one change:
```diff
  Build_Native_Darwin_arm64:
    needs: Build_Linux_X86_64
    runs-on: [self-hosted, macOS, ARM64]
    env:
      build_directory: ${{ github.workspace }}/build
--      build_type: Release
++      build_type: RelWithDebInfo
```
reason: the RelWithDebInfo will add `-gdwarf-4` otherwise, it will stuck when throwing exception.
internal discussion: https://timeplus-workspace.slack.com/archives/C076BLFKGHF/p1730872610469759?thread_ts=1730863194.086949&cid=C076BLFKGHF

**Comment by qijun-niu-timeplus** [comment]
> @qijun-niu-timeplus missing one change:
> 
> ```diff
>   Build_Native_Darwin_arm64:
>     needs: Build_Linux_X86_64
>     runs-on: [self-hosted, macOS, ARM64]
>     env:
>       build_directory: ${{ github.workspace }}/build
> --      build_type: Release
> ++      build_type: RelWithDebInfo
> ```
> 
> reason: the RelWithDebInfo will add `-gdwarf-4` otherwise, it will stuck when throwing exception. internal discussion: https://timeplus-workspace.slack.com/archives/C076BLFKGHF/p1730872610469759?thread_ts=1730863194.086949&cid=C076BLFKGHF

resolved, thanks

**Review by yl-lisen — APPROVED** [review]

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).

**Pull request merged**
